version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
    networks:
      - dotnetniger

  # API Gateway (port 5500)
  gateway:
    build:
      context: .
      dockerfile: DotnetNiger.Gateway/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ServiceDiscovery__Provider=Consul
      - DownstreamServices__Identity__DevUrl=http://identity:8081
      - DownstreamServices__Identity__HealthEndpoint=/api/v1/diagnostics/health
      - DownstreamServices__Identity__SwaggerEndpoint=/swagger/v1/swagger.json
      - DownstreamServices__Community__DevUrl=http://community:8082
      - DownstreamServices__Community__HealthEndpoint=/api/v1/test/health
      - DownstreamServices__Community__SwaggerEndpoint=/swagger/v1/swagger.json
    depends_on:
      - consul
      - identity
      - community
    networks:
      - dotnetniger
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourPassword123!
  #     - MSSQL_PID=Developer
  #   ports:
  #     - "1433:1433"
  #   networks:
  #     - dotnetniger
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql
  #   healthcheck:
  #     test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q "SELECT 1" || exit 1
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  identity:
    build:
      context: .
      dockerfile: DotnetNiger.Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__DefaultConnection=Data Source=data/identity.db
      - Consul__Host=consul
      - Gateway__Enabled=true
      - Gateway__RegistrationUrl=http://gateway:5000/api/service-registry/register
      - Smtp__AppBaseUrl=http://gateway:5000
      - DatabaseProvider=Sqlite
    volumes:
      - identity_data:/app/data
    depends_on:
      - consul
    networks:
      - dotnetniger

  community:
    build:
      context: .
      dockerfile: DotnetNiger.Community/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8082
      - ConnectionStrings__DefaultConnection=Data Source=data/community.db
      - Consul__Host=consul
      - Gateway__Enabled=true
      - Gateway__RegistrationUrl=http://gateway:5000/api/service-registry/register
      - Jwt__Authority=http://identity:8081
      - Jwt__MetadataAddress=http://identity:8081/.well-known/openid-configuration
      - Identity__BaseUrl=http://identity:8081
      - DatabaseProvider=Sqlite
    volumes:
      - community_data:/app/data
    depends_on:
      - identity
      - consul
    networks:
      - dotnetniger

networks:
  dotnetniger:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
  identity_data:
  community_data:
